### ISSUE TITLE
Error in loading the trained model 

### ISSUE THREAD

**Issue by datduong** [jamesmullenbach/caml-mimic#8]
Hi, 

I trained the model based the code here. When I load my model back into python, I get an error. 

This is how I call the command 
```shell 
training.py train_full.csv vocab.csv full conv_attn 100 --filter-size 10 --num-filter-maps 50 --dropout 0.2 --patience 10 --lr 0.0001 --test-model model_best_prec_at_8.pth --gpu --quiet
```

This is the error I get, 
```python 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: inconsistent tensor size, expected tensor [51919 x 100] and src [51920 x 100] to have the same number of elements, but got 5191900 and 5192000 elements respectively at c:\pytorch\torch\lib\th\generic/THTensorCopy.c:86

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training.py", line 355, in <module>
    main(args)
  File "training.py", line 31, in main
    args, model, optimizer, params, dicts = init(args)
  File "training.py", line 48, in init
    model = tools.pick_model(args, dicts)
  File "C:/Users/dat/Dropbox/caml-mimic\learn\tools.py", line 36, in pick_model
    model.load_state_dict(sd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named embed.weight, whose dimensions in the model are torch.Size([51919, 100]) and whose dimensions in the checkpoint are torch.Size([51920, 100]).
```

It seems that the vocab.csv does not match with the vocab in the trained model. Is this because the "unknown token" being added after the vocab.csv was made? 

I feel that there is some strange mismatching here. I check the vocab.csv and it has 51917 lines. 
```shell
wc -l vocab.csv
51917 vocab.csv
```

Thanks.

**Comment by terarachang** [comment]
Hi,
I traced the code and found out that **<PAD>** and **<UNK>** are not included in the vocab.csv.
The vocab. size altogether should be 51917 + 1+1 = 51919.
However, it seems that there's a small bug in **extract_wvs.py**, as the <PAD> token accounts for two lines in the output file of **save_embeddings()**, and thus the vocab. size becomes 51917 + 2+1 = 51920.

**Comment by sarahwie** [comment]
@datduong @terarachang This is fixed in the most updated head of the repo.

**Comment by datduong** [comment]
Thanks.
